### ISSUE TITLE
getResultValues dataframe column names are not CamelCase

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/ODM2PythonAPI#127]
`getResultValues` dataframes seems to be returning column names that are all lowercase rather than `CamelCase`. This is inconsistent with the `CamelCase` keys that all the resulting model have when queried. 

Example:

valueid | resultid | datavalue | valuedatetime | valuedatetimeutcoffset
-- | -- | -- | -- | --
1064 | 1064 | 1.2256 | 2015-11-17 13:55:12 | -7
1065 | 1065 | 71.2000 | 2015-12-01 10:20:00 | -7

This links to ODM2RESTAPI, which currently serializes this data with all lowercase keys. See [odm2restapi issue 55](https://github.com/ODM2/ODM2RESTfulWebServices/issues/55)

**I think future change is needed to make the casing consistent with other query results.**

**Comment by emiliom** [comment]
Has this issue been addressed?

**Comment by lsetiawan** [comment]
Not yet.

**Comment by lsetiawan** [comment]
This issue was addressed in #136.

**Comment by emiliom** [comment]
@lsetiawan So, this issue is closed and you've implemented the fix. As we've discussed, this will be a disruptive change. Ultimately, it's necessary. But I was thinking, what if we deploy it as a less painful, gradual transition? That is, implement it first as a behavior that is *accessible by request* via an optional argument, rather than as the default. The default behavior would remain as it was, to return a dataframe with all-lowercase column names.

What do you think? I'm reopening this issue to expose the discussion.

**Comment by lsetiawan** [comment]
PR #140 has been merged. This issue is resolved.
