### ISSUE TITLE
createDataSet fails to create dataset 

### ISSUE THREAD

**Issue by Castronova** [ODM2/ODM2PythonAPI#21]
The `createDataset` function in createService.py fails.

```
from odm2api.ODM2.services.createService import CreateODM2
writer = CreateODM2(my_local_connection)
writer = ReadODM2(self.connection)
myDataset = writer.createDataset(dstype='my dataset',
                                 dscode='my_dataset',
                                 dstitle='this is my dataset'
                                 dsabstract='some description')
```

**IntegrityError: (IntegrityError) NOT NULL constraint failed: Datasets.DatasetUUID u'INSERT INTO datasets (datasetuuid, datasettypecv, datasetcode, datasettitle, datasetabstract) VALUES (?, ?, ?, ?, ?)' (None, None, None, None, 'test')**

The `createDataset` function sets values for the following variables DatasetTypeCV, DatasetCode, DatasetTitle, DatasetAbstract, DatasetUUID.  However, these variables do not exist in the `models.py` DataSets class, instead they are named **DataSet***.  

To fix, change the variables that are set in `createService.createDataset` to match the variables defined in `models.DataSets`

**Comment by emiliom** [comment]
This issue is ancient. Before closing it (it's probably worth closing just by virtue of it being so old ...), I tried to see if the problem described here no longer exists. That definitely seems to be the case:
- There are no references to lowercase `Dataset*` variables in [createDataset](https://github.com/ODM2/ODM2PythonAPI/blob/master/odm2api/services/createService.py#L67)
- `createDataset` is itself [present as a test](https://github.com/ODM2/ODM2PythonAPI/blob/master/tests/test_odm2/test_createservice.py#L186) that gets run by the CI with every pull requests. The test is passing.

So, I'm calling this resolved and closing the issue.
