### ISSUE TITLE
Prepare for pip install setup and conda recipe

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2PythonAPI#71]
As referenced in https://github.com/ODM2/WOFpy/issues/61, we need @valentinedwv to work with @horsburgh & @sreeder to prepare GitHub releases for corresponding PyPi releases, then communicate with @emiliom & @ocefpaf so that they know to update the Conda recipes.

My understanding of the current situation is that:
* The present an only PyPi release (https://pypi.python.org/pypi/odm2api/0.5.2) was derived from the present head of the master branch, not from the latest release. We need the two to be exactly aligned.
* It might make sense to re-release the master branch, with version "v0.5.3-alpha", to include your TravisCI commits from Oct. 4, then create an aligned release on PyPi with that exact version number and that points to that exact GitHub release.
* There is a, "odmtools" development branch of ODM2API that is substantially ahead of the master branch, so a new release may be in order. Please discuss with with @horsburgh & @sreeder.

**Comment by emiliom** [comment]
A couple of quick comments:
- For conda packaging we work off a github tagged release rather than a pypi package. That's what @ocefpaf recommended in a recent chat (@ocefpaf, please chime him otherwise!). Once I'm pinged that a github release is ready, I'll get things rolling on the conda packaging
- All previous odm2api github releases have been carried out by @sreeder, with input or the ok (I think ...) from @horsburgh. Personally, I think it's best if we keep that "chain of command" -- until @sreeder and @horsburgh say otherwise -- to avoid confusion and stepping on each other's toes

**Comment by ocefpaf** [comment]
> The present an only PyPi release (https://pypi.python.org/pypi/odm2api/0.5.2) was derived from the present head of the master branch, not from the latest release. We need the two to be exactly aligned.

That is desirable.

> For conda packaging we work off a github tagged release rather than a pypi package. That's what @ocefpaf recommended in a recent chat (@ocefpaf, please chime him otherwise!).

That is correct @emiliom. Mostly to avoid the issues like the one above. Usually, for GitHub hosted projects, we consider the GitHub release as the canonical one.

> Once I'm pinged that a github release is ready, I'll get things rolling on the conda packaging

Feel free to ping me too.

**Comment by emiliom** [comment]
Closing. Superseded and addressed by #79
